spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boardtest
    username: root
    password: 9793
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true